Semi-automatic porting and other Workflow script upgrades
RAD:
   examples:radclock_capture_packet.c  and  tests/test_FFclocks.c  :
   - replaced unneeded use of BPF_T_*  by hardcoded values, as not available in
     any .h file for library users
   - commenting out of unneeded and available net/bpf.h

Earthfile:  cosmetic

Workflow_scripts/VM
  Upgrades to numerous scripts to support smarter and more flexible choicies for FFfiles
  and kernel source saving and installing, higher naming consistency, matching
  changes in directory structure in the host machine, better documenting
  of options in comment headers, finished whitespace consistency cleaning
  favouring tabs, and some minor fixes.

  - move_into_srctree:  updated OS version awareness to match more recent Linux ports,
	to block installation of deprecated FFfiles
  - setupVM: improved idempotency and automatic setup of CurrentSource and local
	OriginalSource_OSfullv  saving
  - bashrc:  addition of ANSI colour aliases, adding colour use in some scripts
  - quick_FF_build:  replacement of deb-pkg by bindeb-pkg  to work around
    infuriation package consistency check error blocking building.
	Addition of option to work off test repo instead of the RealRepo for port testing.
  - update_linuxSource:  much better attention to setting of a correct config file,
    and saving, verbosity and commenting of same.

  - save_linuxSource:  new script to save and recover Linux files in /usr/src to
    host OS under FullSource_Linux/$OSfullv/{Original,FF}/ , sufficient to enable recovery of
    the system (debs files) as well as an ability to compile the kernel (source).
    Works around case insensitivity of the macOS filesystem via tarring.

 Workflow_scripts
  - portloop:    largely-automates the "port-loop" process for detailed generation
    of the git commits supporting the porting of FFfiles from an Old OS version
    with an exising port, to a new one. Works for Linux or FreeBSD.
    See header for usage.   Tested and used in committed ports for 4.19.260 and 5.10.149
  - corresponding updates to read

diff --git a/Workflow_scripts/VM/install_earthlyFF b/Workflow_scripts/VM/install_earthlyFF
--- a/Workflow_scripts/VM/install_earthlyFF
+++ b/Workflow_scripts/VM/install_earthlyFF
@@ -4,8 +4,10 @@
 # This script takes deb packages for a new kernel and installs them.
 # Currently packages built by  earthly +{deb,arm}-kernel-build-patched  in the RADclock repo.
 # NOTE:  on the Pi, the /boot partition now appears under /boot/firmware
-
-echo "Installing the earthly generated FFclock deb packages" 
+#
+# options:
+#     -e  dont fetch the debs, just use those already there
+#     -n  use debs for the unpatched kernel (if fetching them)
 
 OS=`uname -s`
 if [ $OS != "Linux" ]; then
@@ -13,71 +15,95 @@ if [ $OS != "Linux" ]; then
 	exit
 fi
 
-
 # Pi detection 
 OnPi="No"
 Arch=`uname -m`
 if [ $Arch == "aarch64" ]; then
-        if [ $OS == "Linux" ]; then
-                OnPi="Yes"
-                ServerHome="darryl@192.168.1.104"
-                Repo="Papers/TSCclock/Programs/V4/RADclock_mycurrent"
-                echo "I see $OS on $Arch, I infer you are on a Pi. Expecting repo at $ServerHome"
-        fi
+	if [ $OS == "Linux" ]; then
+		OnPi="Yes"
+		ServerHome="darryl@192.168.1.104"
+		Repo="Papers/TSCclock/Programs/V4/RADclock_mycurrent"
+		echo "I see $OS on $Arch, I infer you are on a Pi. Expecting repo at $ServerHome"
+	fi
 fi
 
-# Default is to install a patched kernel, see if an unpatched is requested
-if [[ "$1" == "-n" ]]; then
-   echo "=== Will install an UNpatched kernel ==="
-   Patchtype="kernel"
-else
-   echo "=== Will install an FF-patched kernel ==="
-   Patchtype="kernel-patched"
-fi
 
-# Get the location of packages generated by earthly
-if [ $OnPi == "Yes" ]; then
-	RADdir="$ServerHome:$Repo"
-	PkgDir="$RADdir/artifacts/$Patchtype/arm64"
-else
-	Based="$HOME/FFkernel_Work"
-	RADdir="$Based/V4_mountedfrom_Icaro/RADclock_mycurrent"
-	PkgDir="$RADdir/artifacts/$Patchtype/amd64"
-fi
-
-# Get thelatest packages
+### Locate and obtain the packages, and install in /usr/src
 cd /usr/src
-echo "** Grabbing packages from $PkgDir"
-scp $PkgDir/*5.10* .    # hack
-# scp $PkgDir/* .
+
+## Ensure the .debs we want are installed
+if [[ "$1" == "-e" ]]; then
+	echo "Will use the most recent of existing .debs in /usr/src"
+
+else
+
+	# Default is to install a patched kernel, see if an unpatched is requested
+	if [[ "$1" == "-n" ]]; then
+		echo "=== Will install an UNpatched kernel ==="
+		Patchtype="kernel"
+	else
+		echo "=== Will install an FF-patched kernel ==="
+		Patchtype="kernel-patched"
+	fi
+
+
+	## Select the target kernel version
+	#  TODO:  apply checks, and make this smarter, though cant predict what want from running system
+	TargetV="4.19.260"
+
+	# Get the location of packages generated by earthly
+	if [ $OnPi == "Yes" ]; then
+		RADdir="$ServerHome:$Repo"
+		PkgDir="$RADdir/artifacts/$Patchtype/arm64"
+	else
+		Based="$HOME/FFkernel_Work"
+		if [[ "$1" == "-vm" ]]; then	# stored debs from VM
+			echo "Installing deb packages saved from a VM"
+			PkgDir="$Based/V4_mountedfrom_Icaro/FullSource_Linux/$TargetV/kernel-patched" # hack
+		else							# from earthly
+			echo "Installing the earthly generated FFclock deb packages"
+			RADdir="$Based/V4_mountedfrom_Icaro/RADclock_mycurrent"
+			PkgDir="$RADdir/artifacts/$Patchtype/amd64"
+			PkgDir="$PkgDir/$TargetV"
+		fi
+	fi
+
+	# Get the latest packages
+	echo "** Grabbing packages from $PkgDir"
+	scp $PkgDir/*.deb .
+
+fi
+
+## Look at what we have
 ls -ltr |tail -6
-Kname=`ls -tr |tail -3 |grep  linux-image | cut -d'_' -f1 |cut -d'-' -f3-`
-NewSUBLEVEL=`echo $Kname |cut -d'.' -f3`
-echo "Earthly packages are of version $Kname"
+OSfullv=`ls -tr |grep '\.deb' |tail -3 |grep  linux-image | cut -d'_' -f1 |cut -d'-' -f3-`
+NewSUBLEVEL=`echo $OSfullv |cut -d'.' -f3`
+echo "Packages to be installed are of version $OSfullv"
 echo
 
-exit
+
+
 
 # If sublevel of packages is different, source and config actions needed
 if [ $OnPi != "Yes" ]; then
 	echo "=============================================================="
-	#update_linuxSource -d
+#	update_linuxSource
 	echo "=============================================================="
- 	echo "*********** Returning, now in `pwd` *************"
+	echo "*********** Returning, now in `pwd` *************"
 fi
 
 
 # Install debian packages
 echo
-echo "** Newest packages are for a $Kname kernel, Installing them"
+echo "   Installing image"
+dpkg -i linux-image*$OSfullv*.deb
+echo
+echo "** Newest packages are for a $OSfullv kernel, Installing them"
 echo "   Installing headers"
-dpkg -i linux-headers*$Kname*.deb
+dpkg -i linux-headers*$OSfullv*.deb
 echo
 echo "   Installing libc"
-dpkg -i linux-libc*$Kname*.deb
-echo
-echo "   Installing image"
-dpkg -i linux-image*$Kname*.deb
+dpkg -i linux-libc*$OSfullv*.deb
 echo "========================================================================"
 
 
@@ -88,30 +114,32 @@ if [ $OnPi == "Yes" ]; then
 	# Copy the new kernel to the boot partition 
 	cd /boot/firmware
 	ls -altr
-	cp ../{initrd.img,vmlinuz}-$Kname*   . 
+	cp ../{initrd.img,vmlinuz}-$OSfullv*   .
 	
 	# Additional firmware blackmagic to ensure the new kernel can talk to hardware 
 	echo
-	cp -f /usr/lib/linux-image-$Kname/broadcom/*  .
+	cp -f /usr/lib/linux-image-$OSfullv/broadcom/*  .
 	ls -altr
 	
 	# Set it to boot the new kernel
 	echo
-	sed -i"" -E "s/initrd\.img-.*/initrd\.img-$Kname/; s/vmlinuz-.*/vmlinuz-$Kname/"   config.txt
+	sed -i"" -E "s/initrd\.img-.*/initrd\.img-$OSfullv/; s/vmlinuz-.*/vmlinuz-$OSfullv/"   config.txt
 	cat config.txt
 	echo
 	echo '==== Done: "shutdown -r now" should bring up the new kernel'
 else
 	OSv=`uname -r | cut -d'.' -f1-2`
 	SourceDir="/usr/src/linux-source-$OSv"
-    
+
 	echo "Ready to reboot, final check on configuration to ensure success (check, no action): "
-    ConfigFile="$SourceDir/.config"
-    echo "Check signing_key in source config file $ConfigFile"
-    grep signing_key $ConfigFile >> /dev/null
-    if [ $? -ne 0 ]; then
-        echo "  --> signing_key not found in $ConfigFile"
-    fi
+	ConfigFile="$SourceDir/.config"
+	echo "Check signing_key in source config file $ConfigFile"
+	grep signing_key $ConfigFile >> /dev/null
+	if [ $? -ne 0 ]; then
+		echo "  --> signing_key not found in $ConfigFile"
+	else
+		echo "  key is good"
+	fi
 
 	echo ==== Done:, snapshot then reboot with "shutdown -r now"
 fi
