Cleanup for tagged distribution.
Updating of distribution files ChangeLog, NEWS, README.md .

-------------------------------------------
License, Copyright, Attribution restructure

 Project License: no change at BSD-2-Clause, but tweaked COPYING for clarity

 RAD files
  License:		standard BSD-2-Clause per-file text (unchanged)
  Copyright:
    For all core files (.c, .h, and Documentation files), moved to simple
    "Copyright (C) YYYY The RADclock Project (see AUTHORS file)"
	 where YYYY is set to the year of original file creation (typically 2006)
  Attribution:  removed from individual files. Instead a restructure of AUTHORS
  giving more complete information and more historical context of the project.

 FreeBSD FFfiles:
  License:  various BSD 2 or 3 clause licenses  (unchanged)
  Copyright: no change
  Attribution:  given per-file: unchanged for now

 Linux FF files:   [ both 4.19.235 and 5.10.106 ]
  Existing FFfiles:  no change to pre-port header of any kind
  Pure FF files ffclock.{c,h} :
   License:   set to "SPDX-License-Identifier: BSD-2-Clause"
   Copyright:    following Linux convention, no explicit statement
   Attribution:  following Linux convention, authors given with no dates.
     {.c,.h}: {brought up to date, created} with new file description
-------------------------------------------

debian dir:
 - cleaning out all old package files, leaving only daemon startup script

Workflow scripts:
  - smarter update_workingFFsource allowing Linux version sublevel mismatches
  - improved move_into_scrtree
  - fixed issues with createDist

Tools:
  - upgraded  compile_FFkernel  and  update_FFkernelsource, now OS-universal
  - corresponding documentation in the RADclockDoc_guide.md

diff --git a/Tools/compile_FFkernel b/Tools/compile_FFkernel
--- a/Tools/compile_FFkernel
+++ b/Tools/compile_FFkernel
@@ -2,23 +2,100 @@
 
 # Will attempt a kernel build and install of FFclock.
 # Assumes the FFCLOCK kernel config file is already installed
-# Assumes you are in the build directory
-# Will try a fast build, or a full one if -c option given
+# Assumes you are in the build directory, will FFfiles already copied in.
+# FreeBSD: will try a fast build, or a full one if -c option given
+
+# This file adopts the (simplified) compile sections of the VM script
+# quick_FF_build
 
 if [ `id -u` -ne 0 ]; then
-        echo "Sorry `id -un`, this must be run as root"
-        exit 0
+	echo "Sorry `id -un`, this must be run as root"
+	exit 0
 fi
 
-OS=`uname -s`s
-if [ $OS != FreeBSD ]; then
-	echo "This script only tested on FreeBSD, you are on $OS! fingers crossed."
-fi
+OS=`uname -s`
+case $OS in
+	FreeBSD)
+		OSv=`uname -r | cut -d'-' -f1`
+		SourceDir="/usr/src";;
+	Linux)
+		OSv=`uname -r | cut -d'.' -f1-2`
+		SourceDir="/usr/src/linux-source-$OSv";;
+esac
 
 Based=`pwd`
+[[ -e build.log ]] && cp -f $Based/build.log $Based/build_backup.log
 
-pushd /usr/src
+pushd $SourceDir
 echo
+
+#-----------------------------------------------------------------------------#
+if [ $OS == "Linux" ]; then
+
+	echo " *** Remember to answer any interactive qns regarding new packages!!"
+	echo " *** Use:  tail -f build.log  to monitor and check compile progress"
+	if [[ "$1" != "-f" ]]; then
+		echo "Now trying to build clean, executing 'make clean; make deb-pkg' "
+		make clean > $Based/build.log
+		make deb-pkg >> $Based/build.log 2>&1			# make the kernel in the form of a package
+	else
+		echo "Now trying to build fast, executing 'make deb-pkg'"
+		make deb-pkg > $Based/build.log	2>&1			# make the kernel in the form of a package
+		echo
+	fi
+
+	if [ $? -eq 0 ]; then
+		echo "Build successful, now installing generated deb packages"
+		echo
+
+#		echo "First check to see if deb creation altered configuration: "
+#		ConfigFile="$SourceDir/.config"
+#		echo "Check in source config file $ConfigFile"
+#		grep signing_key $ConfigFile >> /dev/null
+#		if [ $? -ne 0 ]; then
+#			echo "  - signing_key not found in $ConfigFile, re-inserting"
+#			scripts/config --set-str MODULE_SIG_KEY certs/signing_key.pem
+#		fi
+
+		# Installation
+		tail -3 $Based/build.log
+		echo
+		InstallPkg="dpkg -i `ls -t ../linux-image-$OSv*.deb |head -1`"
+		echo "** Installing image with: $InstallPkg"
+		$InstallPkg
+		echo
+		InstallPkg="dpkg -i `ls -t ../linux-headers-$OSv*.deb |head -1`"
+		echo "** Installing headers with: $InstallPkg"
+		$InstallPkg
+		echo
+		InstallPkg="dpkg -i `ls -t ../linux-libc-dev_$OSv*.deb |head -1`"
+		echo "** Installing libc-dev with: $InstallPkg"
+		$InstallPkg
+
+
+		# Configuration checks, but not action taken
+		echo
+		echo "Ready to reboot, final check on configuration to ensure success: "
+		ConfigFile="$SourceDir/.config"
+		echo "Check in source config file $ConfigFile"
+		grep signing_key $ConfigFile >> /dev/null
+		if [ $? -ne 0 ]; then
+			echo "  - signing_key not found in $ConfigFile, re-inserting"
+			scripts/config --set-str MODULE_SIG_KEY certs/signing_key.pem
+		fi
+
+		echo
+		echo All good, you can snapshot then reboot your new FFtest kernel with "shutdown -r now"
+	else
+		echo
+		echo '** build failed ** inspect build.log to find out why'
+	fi
+fi
+#-----------------------------------------------------------------------------#
+
+
+#-----------------------------------------------------------------------------#
+if [ $OS == "FreeBSD" ]; then
 
 if [[ "$1" == "-c" ]]; then
 	echo "Now trying to build clean, executing 'make -j2  buildkernel KERNCONF=FFCLOCK'"
@@ -37,5 +114,8 @@ else
 	echo
 	echo '** build failed ** inspect build.log to find out why'
 fi
+
+fi		# OS=FreeBSD
+#-----------------------------------------------------------------------------#
 
 popd
diff --git a/Workflow_scripts/VM/quick_FF_build b/Workflow_scripts/VM/quick_FF_build
--- a/Workflow_scripts/VM/quick_FF_build
+++ b/Workflow_scripts/VM/quick_FF_build
@@ -1,42 +1,42 @@
 #!/bin/bash
 
 if [ `id -u` -ne 0 ]; then
-        echo "Sorry `id -un`, this must be run as root"
-        exit 0
+	echo "Sorry `id -un`, this must be run as root"
+	exit 0
 fi
 
-Based="$HOME/FFkernel_Work"
 OS=`uname -s`
 case $OS in
-        FreeBSD)
-                OSv=`uname -r | cut -d'-' -f1`
-                SourceDir="/usr/src";;
-        Linux)
-                OSv=`uname -r | cut -d'.' -f1-2`
-                SourceDir="/usr/src/linux-source-$OSv";;
+	FreeBSD)
+		OSv=`uname -r | cut -d'-' -f1`
+		SourceDir="/usr/src";;
+	Linux)
+		OSv=`uname -r | cut -d'.' -f1-2`
+		SourceDir="/usr/src/linux-source-$OSv";;
 esac
 
 
 # Determine if will patch the kernel or not
+Based="$HOME/FFkernel_Work"
 if [[ "$1" == "-n" ]]; then
 	echo "=== Will compile and install the current kernel $SourceDir for $OS ==="
 else	
 	echo "=== Will update FF source, copy it to source tree at $SourceDir for $OS, then compile and install ==="
-	update_workingFFsource 5.10.106
+	update_workingFFsource 	# pass explicit argument if not finding desired version
 	echo
-   update_linuxSource -l
-   echo "=============================================================="
+	#update_linuxSource -l		# a hack, dont do this unless it works for you
+	echo "=============================================================="
 	cd $Based
 	move_into_srctree
 fi
+cp -f $Based/build.log $Based/build_backup.log
 
 
 pushd $SourceDir 
 echo
 
-
+#-----------------------------------------------------------------------------#
 if [ $OS == "Linux" ]; then
-	cp -f $Based/build.log $Based/build_backup.log
 
 	CurrSUBLEVEL=`head $SourceDir/Makefile |grep SUBL |cut -d' ' -f3`
    # If sublevel of packages is different, actions needed
@@ -62,15 +62,15 @@ if [ $OS == "Linux" ]; then
 #   fi
 
 
+	echo " *** Remember to answer any interactive qns regarding new packages!!"
+	echo " *** Use:  tail -f build.log  to monitor and check compile progressing"
 	if [[ "$1" != "-f" ]]; then
-		echo "Now trying to build clean, executing 'make clean; make deb-pkg' - remember to hit rtn to ans cmdline qn!"
+		echo "Now trying to build clean, executing 'make clean; make deb-pkg' "
 		make clean > $Based/build.log
 		make deb-pkg >> $Based/build.log 2>&1			# make the kernel in the form of a package
-		#Y				# answers the initial cmdline qn regarding FFclock inclusion
 	else
 		echo "Now trying to build fast, executing 'make deb-pkg'"
 		make deb-pkg > $Based/build.log	2>&1			# make the kernel in the form of a package
-		#Y				# answers the initial cmdline qn regarding FFclock inclusion
 		echo
 	fi
 
@@ -82,17 +82,17 @@ if [ $OS == "Linux" ]; then
 		ConfigFile="$SourceDir/.config"
 		echo "Check in source config file $ConfigFile"
 		grep signing_key $ConfigFile >> /dev/null
-    	if [ $? -ne 0 ]; then
-        	echo "  - signing_key not found in $ConfigFile, re-inserting"
-        	scripts/config --set-str MODULE_SIG_KEY certs/signing_key.pem
-    	fi
+		if [ $? -ne 0 ]; then
+			echo "  - signing_key not found in $ConfigFile, re-inserting"
+			scripts/config --set-str MODULE_SIG_KEY certs/signing_key.pem
+		fi
 	
 		ConfigFile="/boot/config-$OSv.$CurrSUBLEVEL"
 		echo "Check in boot   config file $ConfigFile"
-    	grep signing_key $ConfigFile >> /dev/null
-    	if [ $? -ne 0 ]; then
-        	echo "  - signing_key not found in $ConfigFile"
-    	fi
+		grep signing_key $ConfigFile >> /dev/null
+		if [ $? -ne 0 ]; then
+			echo "  - signing_key not found in $ConfigFile"
+		fi
 
 		# Installation
 		tail -3 $Based/build.log
@@ -110,17 +110,17 @@ if [ $OS == "Linux" ]; then
 		$InstallPkg
 
 
-		# Configuration checks, but not action taken
+		# Configuration checks, but no action taken
 		echo
 		echo "Ready to reboot, final check on configuration to ensure success: "
-    	ConfigFile="$SourceDir/.config"
+		ConfigFile="$SourceDir/.config"
 		echo "Check in source config file $ConfigFile"
-    	grep signing_key $ConfigFile >> /dev/null
-    	if [ $? -ne 0 ]; then
-        	echo "  - signing_key not found in $ConfigFile, re-inserting"
-        	scripts/config --set-str MODULE_SIG_KEY certs/signing_key.pem
-        	#cat /root/FFkernel_Work/RPi_toolkit/sshaccessline >> /boot/firmware/sysconf.txt
-    	fi
+		grep signing_key $ConfigFile >> /dev/null
+		if [ $? -ne 0 ]; then
+			echo "  - signing_key not found in $ConfigFile, re-inserting"
+			scripts/config --set-str MODULE_SIG_KEY certs/signing_key.pem
+			#cat /root/FFkernel_Work/RPi_toolkit/sshaccessline >> /boot/firmware/sysconf.txt
+		fi
 	
 		ConfigFile="/boot/config-$OSv.$CurrSUBLEVEL"
 		echo "Diff between boot and source config:"
@@ -128,11 +128,11 @@ if [ $OS == "Linux" ]; then
 		echo "===================================="
 
 		echo "Check in boot   config file $ConfigFile"
-    	grep signing_key $ConfigFile >> /dev/null
-    	if [ $? -ne 0 ]; then
-        	echo "  - signing_key not found in $ConfigFile"
+		grep signing_key $ConfigFile >> /dev/null
+		if [ $? -ne 0 ]; then
+			echo "  - signing_key not found in $ConfigFile"
 			#cp $SourceDir/.config $ConfigFile 
-    	fi
+		fi
 
 
 		echo
@@ -142,9 +142,10 @@ if [ $OS == "Linux" ]; then
 		echo '** build failed ** inspect build.log to find out why'
 	fi
 fi
+#-----------------------------------------------------------------------------#
 
 
-
+#-----------------------------------------------------------------------------#
 if [ $OS == "FreeBSD" ]; then
 
 if [ "$1" == "-w" ]; then
@@ -163,7 +164,7 @@ fi
 if [ $? -eq 0 ]; then    # if previous command exits with success
 	if [ "$1" == "-w" ]; then
 		tail -3 $Based/buildworld.log
-    		echo Buildworld successful!
+		echo Buildworld successful!
 		echo
 	fi
 
@@ -177,8 +178,8 @@ if [ $? -eq 0 ]; then    # if previous command exits with success
 	
 	if [ $? -eq 0 ]; then    # if previous command exits with success
 		tail -3 $Based/build.log 
-	    #if [ "$1" == "-w" ]; then	
-	    if [ "-w" == "-w" ]; then	
+		#if [ "$1" == "-w" ]; then
+		if [ "-w" == "-w" ]; then
 			echo Build successful, now executing 'make installkernel KERNCONF=FFCLOCK'
 			make installkernel KERNCONF=FFCLOCK		> $Based/install.log
 			echo All good, you can snapshot then reboot
@@ -194,10 +195,11 @@ if [ $? -eq 0 ]; then    # if previous command exits with success
 		echo '** build failed ** inspect build.log to find out why'
 	fi
 else
-    echo
-    echo '** buildworld failed ** inspect buildworld.log to find out why'
+	echo
+	echo '** buildworld failed ** inspect buildworld.log to find out why'
 fi
 
 fi		# OS=FreeBSD
+#-----------------------------------------------------------------------------#
 
 popd
